name=GY33_Colour_Sensor
version=1.1.2
author=You-010
maintainer=You-010 <276804073+You-010@users.noreply.github.com>
sentence=A library for the GY-33 (TCS34725) colour sensor module (I2C and UART).
paragraph=Supports both I2C and UART modes for the MCU-based GY-33 color sensor module. Ported from the MicroPython library by QuirkyCort.
category=Sensors
url=https://github.com/You-010/GY33_Arduino
architectures=*
includes=GY33.h
